### ISSUE TITLE
Ticking Freeze/Crash

### ISSUE THREAD

**Issue by Inonedn** [GeheimagentNr1/RapidLeafDecay#1]
**Versions**
Minecraft Version: 1.18
Minecraft Forge Version: 38.0.15
Mod Version: [e.g. 2.0.0]

**Log files**
Please append the log, debug-log and if available the crash-log files.

**Describe the bug**
Sometimes, It locks me out of the world until I delete the config file
[crash-2021-12-08_20.37.23-server.txt](https://github.com/GeheimagentNr1/RapidLeafDecay/files/7681575/crash-2021-12-08_20.37.23-server.txt)

**Comment by GeheimagentNr1** [comment]
Seams more like a FML/Forge or a Nightconfig error.  
Probably I cannot do anything about that.
