### ISSUE TITLE
Mod forces doubleclick in GUI and game itself

### ISSUE THREAD

**Issue by Jessman5** [GeheimagentNr1/RapidLeafDecay#2]
**Versions**
Minecraft Version: 1.18.1
Minecraft Forge Version: 39.0.8
Mod Version: latest

**Describe the bug**
As soon as I load this mod into my game, it forces me to use double click everywhere. in the GUI and in the game itself.

**To Reproduce**
Load the mod.

**Expected behaviour**
Not to force double click.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>Invalid</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

*   The issue could not be reproduced.

**TODOs:**

*   [x] Test with Minecraft 1.18.1, Forge 39.0.8 and Mod version 2.0.0, if the issue can be reproduced.
