### ISSUE TITLE
[Crash / 1.19.2] Crash on loading/creating world.

### ISSUE THREAD

**Issue by murao-kun** [GeheimagentNr1/RapidLeafDecay#4]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.1.2
Mod Version: 2.0.1

**Log files**
[crash-2022-08-23_15.10.48-server.txt](https://github.com/GeheimagentNr1/RapidLeafDecay/files/9402437/crash-2022-08-23_15.10.48-server.txt)
[debug.log](https://github.com/GeheimagentNr1/RapidLeafDecay/files/9402434/debug.log)
[latest.log](https://github.com/GeheimagentNr1/RapidLeafDecay/files/9402436/latest.log)

**Describe the bug**
Crash happening on world loading/creation.

**Comment by GeheimagentNr1** [comment]
Does it always crash, when you try to join a world, or only once in a while?
What mod pack are you using?

**Comment by murao-kun** [comment]
It is happening time to time, not every time.
Modpack is custom, for a public release, but not yet, still in development.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Critical Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>2.0.2</td></tr><tr><th>Fix release date:</th><td>01.09.2022</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Search for solution to solve this issue, without recreating this issue. 

**Fix information**

Added check to mod for Minecraft versions 1.17.1-1.19.2 and future versions.

**Comment by GeheimagentNr1** [comment]
The issue should hopefully be fixed with version 2.0.2.  
I did my best to prevent the issue from future occurrence.

**Comment by murao-kun** [comment]
Thank you!
